from django.urls import path
from . import views


urlpatterns = [

    path('view_project/<int:project_id>',
         views.view_project,
         name='view_project'),
    path('drag_list',
         views.drag_list,
         name='drag_list'),
    path('drag_task/<int:project_id>',
         views.drag_task,
         name='drag_task'),
    path('edit_list/<int:list_id>',
         views.edit_list,
         name='edit_list'),
    path('delete_list/<int:list_id>',
         views.delete_list,
         name='delete_list'),
    path('create_task/<int:list_id>',
         views.create_task,
         name='create_task'),
    path('delete_task/<int:task_id>',
         views.delete_task,
         name='delete_task'),
    path('delete_all_task_list/<int:list_id>',
         views.delete_all_task_list,
         name='delete_all_task_list'),
    path('create_priority_task/<int:project_id>',
         views.create_priority_task,
         name='create_priority_task'),
    path('edit_priority/<int:priority_id>',
         views.edit_priority,
         name='edit_priority'),
    path('delete_priority/<int:priority_id>',
         views.delete_priority,
         name='delete_priority'),
]
