# Generated by Django 3.2.5 on 2021-09-25 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prioritytask',
            old_name='description',
            new_name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
