# Generated by Django 3.2.5 on 2021-10-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211023_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='final_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Final Time'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Starting Time'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=55, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
