# Generated by Django 3.2.5 on 2021-08-02 18:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'Doing'), (3, 'Done')], default=1),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 2, 15, 11, 28, 542281), editable=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.prioridadetarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.tipotarefa'),
        ),
    ]
