# Generated by Django 3.2.5 on 2021-08-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_auto_20210815_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
