# Generated by Django 3.2.5 on 2021-08-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_auto_20210802_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.prioridadetarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.tipotarefa'),
        ),
    ]
