# Generated by Django 3.2.5 on 2021-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_alter_projeto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data_final',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descricão'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
    ]
