# Generated by Django 3.2.5 on 2021-08-02 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_auto_20210802_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(default=datetime.datetime(2021, 8, 2, 18, 32, 47, 666972, tzinfo=utc), editable=False),
        ),
    ]
