# Generated by Django 3.2.5 on 2021-08-02 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_alter_tarefa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateField(default=datetime.date(2021, 8, 2), editable=False),
        ),
    ]
