# Generated by Django 3.2.5 on 2021-08-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_auto_20210819_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listatarefas',
            options={'ordering': ['numero'], 'verbose_name': 'Lista de Tarefas', 'verbose_name_plural': 'Listas de Tarefas'},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prioridadetarefa',
            name='descricao',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.listatarefas'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.prioridadetarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.tipotarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='', max_length=55, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tipotarefa',
            name='descricao',
            field=models.CharField(max_length=55),
        ),
    ]
