# Generated by Django 3.2.5 on 2021-08-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_auto_20210828_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoTarefa',
            new_name='PrioridadeTarefaProjeto',
        ),
        migrations.RenameModel(
            old_name='PrioridadeTarefa',
            new_name='TipoTarefaProjeto',
        ),
        migrations.AlterModelOptions(
            name='prioridadetarefaprojeto',
            options={'verbose_name': 'Prioridade', 'verbose_name_plural': 'Prioridades'},
        ),
        migrations.AlterModelOptions(
            name='tipotarefaprojeto',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
    ]
