# Generated by Django 3.2.5 on 2021-08-02 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0006_alter_tarefa_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
