# Generated by Django 3.2.5 on 2021-08-02 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('projetos', '0007_auto_20210802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tarefas', models.ManyToManyField(to='projetos.Tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
    ]
