# Generated by Django 3.2.5 on 2021-09-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0007_auto_20210829_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.prioridadetarefaprojeto'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.tipotarefaprojeto'),
        ),
    ]
