# Generated by Django 3.2.5 on 2021-10-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day of the event')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Starting Time')),
                ('final_time', models.TimeField(blank=True, null=True, verbose_name='Final Time')),
            ],
        ),
    ]
